set -g prefix C-a
bind C-a send-prefix

set -g default-terminal "screen-256color"

set -sg escape-time 0               # disable delay between keystrokes
set -g base-index 1                 # base index for windows
set -g pane-base-index 1            # base index for panes
set -g renumber-windows on          # auto renumber windows when one is closed
set -g monitor-activity on          # active windows are highlighted in status bar

bind R source-file ~/.tmux.conf     # reload tmux dotfile with Prefix+R

set -g status-keys vi               # vi-like editing within the status bar
setw -g mode-keys vi                # vi-like navigation within a buffer

# h,j,k,l to switch between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
