brew "gh"
brew "neovim"
brew "tree-sitter-cli"
brew "tmux"
brew "ripgrep"
brew "fzf"
brew "stow"
brew "bat"
brew "eza"
brew "uv"
brew "fnm"
brew "cmake"
brew "colima"
brew "docker"
brew "docker-compose"

cask "google-chrome"
cask "ghostty"
cask "visual-studio-code"
cask "rectangle"
cask "tailscale-app"
cask "vlc"

cask "claude-code@latest"
cask "codex"
cask "copilot-cli"
# Antigravity CLI installs with:
# curl -fsSL https://antigravity.google/cli/install.sh | bash

cask "gcloud-cli"
